### PR TITLE
Fixed a problem that before_llm_cb return value is not canceled even if False when the return value is coroutine.

### PR DESCRIPTION
**Pull request by Tanesan**
https://github.com/livekit/agents/issues/958#issue-2600681919

### CODE REVIEW

**Review by theomonnom — APPROVED** [review]
lgtm!

**Comment by theomonnom** [comment]
Can you sign the CLA :)

**Comment by Tanesan** [comment]
I did it, thank you :)

**Comment by theomonnom** [comment]
Thanks!

**Comment by martin-purplefish** [comment]
Just a nit - https://github.com/livekit/agents/blob/b16b24654e04805662c22fe12ef43c66064177f6/livekit-agents/livekit/agents/pipeline/pipeline_agent.py#L22C1-L22C18 - the type should have Awaitable[Literal[False]] as well

**Comment by Tanesan** [comment]
@martin-purplefish 
I forgot! Thanks for pointing it out. I've fixed it!
https://github.com/livekit/agents/pull/965

**Pull request merged**
