### PR TITLE
endpoint prediction

### PR DESCRIPTION
**Pull request by jeradf**
Add experimental endpoint prediction model

### CODE REVIEW

**Comment by theomonnom** [comment]
Nice man! I think we should move the end of utterance model inside its own model. But let's sync tmrw

**Comment by theomonnom** [comment]
just created a livekit org: https://huggingface.co/livekit
let's upload our model there?

**Comment by bradyneal** [comment]
Any update on this?

**Comment by theomonnom** [comment]
> Any update on this?

This was moved [here](https://github.com/livekit/agents/pull/1133)

**Pull request closed without merging**
