### PR TITLE
disable http server by default

### PR DESCRIPTION
**Pull request by theomonnom**
We don't have much usage for it today (except health_check) 

Also reduce UPDATE_LOAD_INTERVAL from 10.0 to 5.0

### CODE REVIEW

**Review by nbsp — APPROVED** [review]

**Review by davidzhao — APPROVED** [review]
looks fine, but I think we would benefit from a more dynamic update mechanism.. where we run the loop more frequently, but send an update if:
* load changes by more than 10%
* it's been more than 5 seconds

that'll allow us to react faster to load changes

**Comment by davidzhao** [comment]
@theomonnom I'm also not sure about disabling the server by default.. perhaps don't fail the process if it's in conflict?

**Comment by theomonnom** [comment]
> looks fine, but I think we would benefit from a more dynamic update mechanism.. where we run the loop more frequently, but send an update if:
> 
> * load changes by more than 10%
> * it's been more than 5 seconds
> 
> that'll allow us to react faster to load changes

Makes sense, will plan this one for another PR

**Comment by davidzhao** [comment]
default behaviors are tricky to change.. as it breaks user's expectations

**Pull request closed without merging**
