### PR TITLE
add more context to logs

### PR DESCRIPTION
**Pull request by theomonnom**
- extra is shown by default in both, dev and prod
- removed colorlog and python-json-logger dependencies (current code is based on them)

### CODE REVIEW

**Comment by theomonnom** [comment]
agent_identity will be in another PR

**Review by davidzhao — APPROVED** [review]
lg!

should some of this be in the python SDK? seems like we might want the json/colored loggers in multiple places

**Comment by theomonnom** [comment]
> lg!
> 
> should some of this be in the python SDK? seems like we might want the json/colored loggers in multiple places

I think python-sdks shouldn't be too opinionated. In agents we're doing it but I'm going to allow to bypass these configurations.

**Comment by davidzhao** [comment]
> I think python-sdks shouldn't be too opinionated. In agents we're doing it but I'm going to allow to bypass these configurations.

I think practically, users would just want sane defaults for everything. it'd be great to standardize things like logging on the python stack. but we that doesn't have to block this PR

**Pull request merged**
