### PR TITLE
Add support for boosting for Google STT

### PR DESCRIPTION
**Pull request by martin-purplefish**

### CODE REVIEW

**Comment by martin-purplefish** [comment]
PTAL @theomonnom @davidzhao https://cloud.google.com/speech-to-text/docs/adaptation-model

**Review by davidzhao — APPROVED** [review]
lgtm

**Comment by theomonnom** [comment]
We should mb offer a similar API to what we do for DG? https://github.com/livekit/agents/blob/509c94ae1c3c558c7eeb118aeba3b67fa80570d0/livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram/stt.py#L117

**Comment by martin-purplefish** [comment]
@theomonnom good call! https://github.com/livekit/agents/pull/1067

**Pull request merged**
